- name: Performing initial ProxMox host configuration
  hosts: proxmox
  vars_files:
    - vars.yml
  handlers:
    - name: restart_sshd
      service:
        name: sshd
        state: restarted
    - name: restart_chronyd
      service:
        name: chronyd
        state: restarted
  tasks:
    - name: Installing packages on {{ inventory_hostname }}
      apt:
        pkg:
          - vim
          - nload
          - fio
          - net-tools
          - openvswitch-switch

    - name: Disabling the PVE banner service
      service:
        name: pvebanner
        state: stopped
        enabled: false

    - name: Setting the login banner in /etc/motd
      lineinfile:
        path: /etc/motd
        line:  "{{ motd }}"
        owner: root
        group: root
        mode: 0644
      notify:
        - restart_sshd

    - name: Removing 10-uname to prevent kernel logging info
      file:
        path: /etc/update-motd.d/10-uname
        state: absent

    - name: Set timezone to UTC
      timezone:
        name: UTC

    - name: Add in NTP servers
      lineinfile:
        path: /etc/chrony/chrony.conf
        line:  "{{ ntp_server }}"
        state: present
      notify:
        - restart_chronyd

    - name: Remove default NTP pool
      lineinfile:
        path: /etc/chrony/chrony.conf
        line:  "pool 2.debian.pool.ntp.org iburst"
        state: absent
      notify:
        - restart_chronyd

    - name: Configure DNS
      shell: pvesh set /nodes/{{ node }}/dns --search {{ search_domain }} --dns1 {{ dns_server1 }} --dns2 {{ dns_server2 }}

    - name: Add network comments on {{ iface_1 }}
      shell: pvesh set /nodes/{{ node }}/network/{{ iface_1 }} --type eth --comments "SPAN Interface"

    - name: Reload network interfaces
      shell: ifreload -a

    - name: Adding NFS storage {{ nfs_storage }} on {{ inventory_hostname }}
      blockinfile:
        path: /etc/pve/storage.cfg
        block: |
          nfs: {{ nfs_storage }}
                   export {{ nfs_path }}
                   path /mnt/pve/{{ nfs_storage }}
                   server {{ nfs_ip }}
                   content {{ nfs_content }}
                   prune-backups keep-all=1

    - name: Rename the local storage to {{ node }}
      replace:
        path: /etc/pve/storage.cfg
        regexp: 'local'
        replace: "{{ node }}"
