- name: Deploying a virtual machine
  hosts: proxmox
  vars:
    hostname: caerus-pmx
    vmid: 1000
    cores: 4
    memory: 4096
    ostype: l26
    bootonhoststartup: 1
    scsihw: virtio-scsi-single
    diskID: scsi0
    disklocation: caerus-nfs-datastore
    # Size is in GB
    disksize: 10
    netID: net0
    nettype: virtio
    netbridge: vmbr0
    isodatastore: caerus-nfs-iso
    iso: ubuntu-22.04.4-live-server-amd64.iso
    vmdesc: My VM
    vmname: MyVM
  vars_prompt:
    - name: deploymenttype
      prompt: Select "NewVM" , "FromTemplate" , or "LXC" to deploy the type of VM required

  tasks:
    - name: Deploying {{ deploymenttype }} named {{ vmname }} on {{ inventory_hostname }}
      shell: 	pvesh create /nodes/{{ hostname }}/qemu --vmid {{ vmid }} --cores {{ cores }} --memory {{ memory }} --ostype {{ ostype }} --onboot {{ bootonhoststartup }} --scsihw {{ scsihw }} --{{ diskID }} {{ disklocation }}:{{ disksize }} --{{ netID }} model={{ nettype }},bridge={{ netbridge }} --cdrom {{ isodatastore }}:iso/{{ iso }} --description "{{ vmdesc }}" --name "{{ vmname }}" --start 1
      when: deploymenttype == "NewVM"

    - name: Gathering config for newly created {{ vmname }} on {{ inventory_hostname }}
      shell: 	qm config {{ vmid }}
      register: qmconfig
      when: deploymenttype == "NewVM"

    - debug: Printing the config for newly created {{ vmname }}
        var: "{{ qmconfig.stdout_lines }}""
# VM Deployment from template
#shell: pvesh create /nodes/{{ inventory_hostname }}/qemu --vmid 1000 --cores 4 --memory 4096 --ostype l26 --onboot 1 --scsihw virtio-scsi-single --scsi0 caerus-nfs-datastore:10 --net0 model=virtio,bridge=vmbr0 --cdrom caerus-nfs-iso:iso/ubuntu-22.04.4-live-server-amd64.iso --description "My VM" --name "MyVM" --start 1


